# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c077b3f9efe881954da4ef8b3a390f921569289b3e82561f0ea7f9343dbc93ce0e748c9a6f44390e4b0cd0dc2bed8dcafa37ad735a13e846e8bcb928c82f6830

test:
  secret_key_base: 8bea0226ec56c6a09ee03ba70d9c9774f7f478286b1da9bee62b88ab01df54c45966938c35d4b9e9f3844001dacee17a590aae9b4c7522960cce8a6fd76c34a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
